
import './globals.css'
import { Poppins, Montserrat } from 'next/font/google'
import { AppContextProvider } from './Context/store'
import { SkeletonTheme } from 'react-loading-skeleton';
import LoadGoogleMaps from './loadGoogle'
import  {LogIn} from './(auth)/(login)/logIn'
import {SignUp} from '@/app/(auth)/(signup)/signUp'
import { NavBar } from './NavBar';
import Footer from './footer';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import SessionLogIn from './(auth)/sessionLogIn';




const poppins = Poppins({ subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
})

const montserrat = Montserrat({ subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: {children: React.ReactNode}) {
  // Remove this from
  const supabase = createServerComponentClient({ cookies })
  const { data } = await supabase.auth.getSession()
  // sessionLogIn({data:data.session})

  
  
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={`${poppins.className} relative`}>
          <NavBar montserrat={montserrat}></NavBar>
          <main  className='main-children min-h-[90vh]'>
            <SkeletonTheme baseColor="rgb(211, 211, 211)" highlightColor="white">
                {children}
            </SkeletonTheme>
          </main>
          <LogIn/>
          <SignUp/>
          <LoadGoogleMaps/>
          <SessionLogIn data ={data.session}/>
          <Footer/>
        </body>
      </AppContextProvider>
    </html>
  )
}
