import Link from 'next/link'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={poppins.className}>
        <nav>
          <Link className='nav-logo' href="/">
            <svg className='nav-logo-svg' data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500">
                <circle className="b fill-light" cx="236.72" cy="399.82" r="33.28"/>
                <path className="fill-primary" d="M330.79,366.79h.03S218.42,46.72,218.42,46.72C207.08,14.56,173.34-3.39,140.73,4.14c-3.84,.89-6.04,4.96-4.73,8.69l41.51,118.32,58.99,168.21s-.09,0-.14,0c-55.13,0-99.83,44.69-99.83,99.83s44.69,99.83,99.83,99.83,99.83-44.69,99.83-99.83c0-11.34-1.92-22.23-5.4-32.38Zm-94.43,85.62c-29.4,0-53.24-23.84-53.24-53.24s23.84-53.24,53.24-53.24,53.24,23.84,53.24,53.24-23.84,53.24-53.24,53.24Z"/>
                <path className="fill-primary" d="M452.58,250.44c-10.34,14.4-27.67,23.43-47.03,22.09-26.25-1.81-47.53-23.08-49.34-49.33-2.15-31.11,22.46-57.02,53.11-57.02,18.75,0,35.22,9.7,44.7,24.34,1.71,2.64,5.08,3.67,8,2.5l30.6-12.24c3.76-1.51,5.32-6,3.3-9.52-18.13-31.55-52.99-52.26-92.48-50-48.64,2.79-91.6,46.27-93.84,94.94-2.64,57.28,43.02,104.55,99.72,104.55,37.06,0,69.39-20.19,86.61-50.17,2.02-3.51,.46-8-3.31-9.51l-32.21-12.88c-2.82-1.13-6.06-.21-7.83,2.25Z"/>
                <path className="fill-primary" d="M177.71,192.03l-45.42-12.95L11.71,144.7c-3.79-1.08-7.73,1.35-8.39,5.24-5.57,32.99,14.36,65.61,47.14,75.02l154.24,44.03-26.99-76.96Z"/>
              </svg>
            <p>Clippr.</p>
            </Link>
          <Link href="/discover">
            <section className='nav-search'>
              <div>
                Location
              </div>
              <div>
                Time
              </div>
              <svg version="1.1" className='nav-svg-profile' width="20" height="20" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 408.1 408" xmlSpace="preserve">
                <path d="M402,372L298,268c51-65,46-160-14-219C253,18,211,0,166,0S80,17,49,49C17,80,0,122,0,166s17,86,49,118c31,31,73,49,118,49
                  c37,0,73-12,102-35l104,104c4,4,9,6,15,6c6,0,11-2,15-6C410,394,410,380,402,372z M78,254c-23-23-36-55-36-88s13-64,36-88
                  c24-23,55-36,88-36s64,13,88,36c48,49,48,127,0,176c-23,23-55,36-88,36C133,291,102,278,78,254z"/>
              </svg>
            </section>
          </Link>
          <div className='nav-links'>
            <Link href="/barber">
            <svg className='nav-svg-profile' width="40" height="40" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M68 40C68 55.464 55.464 68 40 68C24.536 68 12 55.464 12 40C12 24.536 24.536 12 40 12C55.464 12 68 24.536 68 40Z" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M58.3013 61.192C53.3935 65.4341 46.9966 68 40.0004 68C33.0041 68 26.6071 65.434 21.6992 61.1918C23.0685 58.9261 25.1923 57.1319 27.8006 56.1934C35.6862 53.3561 44.3142 53.3561 52.1998 56.1934C54.8082 57.1319 56.9321 58.9262 58.3013 61.192Z" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M44.9581 46.1552C48.0026 44.6538 50.2028 41.8537 50.9413 38.5404L51.0113 38.2265C51.7558 34.8862 50.9692 31.388 48.8665 28.688L48.7564 28.5466C46.6536 25.8465 43.4227 24.2676 40.0004 24.2676C36.5781 24.2676 33.3472 25.8465 31.2445 28.5466L31.1344 28.688C29.0316 31.388 28.245 34.8862 28.9895 38.2265L29.0595 38.5404C29.798 41.8537 31.9982 44.6538 35.0427 46.1552C38.1682 47.6964 41.8327 47.6964 44.9581 46.1552Z" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
